# Generated by Django 5.1.5 on 2025-02-10 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CrustType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_main.cheese')),
                ('crust', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_main.crusttype')),
                ('size', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_main.pizzasize')),
                ('sauce', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_main.sauce')),
                ('toppings', models.ManyToManyField(to='pizza_main.topping')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=100)),
                ('address', models.TextField(default='Unknown Address')),
                ('card_number', models.CharField(default='0000000000000000', max_length=16)),
                ('card_expiry', models.CharField(default='00/00', max_length=5)),
                ('card_cvv', models.CharField(default='000', max_length=3)),
                ('pizza', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_main.pizza')),
            ],
        ),
    ]
