# Generated by Django 5.1.5 on 2025-02-10 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='crusttype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='cheese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_main.cheese'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_main.crusttype'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sauce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_main.sauce'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_main.pizzasize'),
        ),
        migrations.AlterField(
            model_name='pizzasize',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
