# Generated by Django 5.1.5 on 2025-02-12 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_main', '0003_pizza_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
