# Generated by Django 5.1.5 on 2025-02-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_main', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='address',
            field=models.TextField(default='DCU'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='Gordon Ramsay', max_length=100),
        ),
    ]
